### ISSUE TITLE
Clarifications on 0 GC retrieval?

### ISSUE THREAD

**Issue by pranasblk** [lmdbjava/lmdbjava#120]
Does invocation creates object/allocates system memory?
`DirectBuffer rez = db.get(transaction, keyBuf);`

If yes, is there way to pass destination buffer to the method call to avoid memory allocation/object creation?
First impression from skimming code, invocation does not create Java object, but allocates native block of memory ... 
What kind and how much overhead is expected if multiple thread retrieves data in a long running transaction?

**Comment by benalexau** [comment]
In a nutshell, repeatedly invoking this method will not produce Java objects.

This is because the majority of Java to LMDB interfacing happens in [`BufferProxy`](https://github.com/lmdbjava/lmdbjava/blob/master/src/main/java/org/lmdbjava/BufferProxy.java) implementations. You're using `DirectBuffer` above, so that would be [`DirectBufferProxy`](https://github.com/lmdbjava/lmdbjava/blob/master/src/main/java/org/lmdbjava/DirectBufferProxy.java). If you read through the code you can see a `ThreadLocal`-bound pool is used so the `DirectBuffer` instances are recycled. 

Admittedly there's an allocation during the initial "get" for each thread, but the same `DirectBuffer` instance is repeatedly reused for subsequent "get" style operations. This is safe given one of the fundamental rules of LMDB is never modify any buffers you have retrieved (as they map to the underlying LMDB file) and they are only valid until the next "get" operation or the transaction ends (as the pointers will move to some other memory).

At a practical level most of the GC in an LmdbJava application will be the creation and disposal of `Txn` instances. As discussed in an earlier ticket (#119) it is generally desirable to minimise transactions anyway.

Of course LMDB does not assist with how you create and recycle buffers you may pass to LMDB in mutation or other operations. I usually use `DirectBuffer` in my applications (being a heavy SBE user) and these are easily managed and recycled given the numerous "wrap" methods.

Hope this answers your query.

**Comment by pranasblk** [comment]
G'Day,

It would be nice to have option for caller to control memory (passing buffer as second parameter), but it's not required for the activity I'm concerned right now. It's great project in many aspects.

Thanks for very practical insights about proper real-life usage!

**Comment by benalexau** [comment]
Due to the method signature complexity I'm reluctant to add an extra two buffer parameters (one for the LMDB "out" key pointer and one for the LMDB "out" value pointer) to enable user-controlled return buffers. I have written lots of LmdbJava applications over the years and never noticed a performance issue due to allocation or GC pressure (in my experience bottlenecks are commonly in areas like LMDB balancing the B+ Tree, disk or network I/O, third party libraries and application-specific algorithms like delta encoding). 

If your application use cases allow it, you can usually get maximum LMDB performance by following some simple suggestions like limit the transactions, share the transaction instance, adopt an application-specific temporal granularity that allows simple operational management and batch partitioning, insert in key order wherever possible (or, if not possible, rebuild the file afterwards in key order), try to store related values in a single entry (eg store related integers as a single array value and compress it with something like FastPFOR etc). These suggestions also ensure the smallest possible LMDB database sizes.

If precise buffer control is a concern though, one can always provide their own `BufferProxy`. It's a `public abstract class` so intended for end user implementation. This would allow a caller to manage their buffers in whatever way they desire (eg consult a `ThreadLocal` for the buffer they want LmdbJava to use).
