### ISSUE TITLE
Proper way to handle map size reached (MapFullException)

### ISSUE THREAD

**Issue by mquigley** [lmdbjava/lmdbjava#126]
There is no way for my application to know the size of the database beforehand. It could be working on a small sample size or an extremely large set of data. The user adds data themselves, so I don't have a way to hardcode or dynamically determine what to set a map size to be at database creation. It seems the only feasible option is to dynamically grow the map size if possible. Is there best practices for this? I saw [this todo](https://github.com/lmdbjava/lmdbjava/issues/65#issuecomment-396766134).

Let me be more specific about the problems. 

1. How do you actually grow the map size at runtime?

My guess is that I have to just close down my existing `Env` and `Dbi`s and recreate all of them. Even my simple example below would have to be refactored.

2. Is everything in the transaction lost after the map size is exceeded?

Doing single write transactions is extremely slow; on my Mac it may take 3 seconds to do 10_000 simple writes, but on my Windows box it takes 30 seconds! So I will keep a long-lived write transaction. But if the database runs out of space at some point in that life, then all of those writes are lost, and are unrecoverable. In the sample I have below, with a loop of transactions, it's true that I could just run the method again, but you can imagine how that would be really inefficient.

I've put a code sample for us to reference below. It gets to somewhere between 200k and 300k before failing. Note that it's a small 10MB map size, on purpose, to expose how to dynamically grow the database in a code sample.

P.S. As a bonus could you tell me if I'm creating my keys correctly in `getKey()` to work with `MDB_INTEGERKEY`?

```java
    import org.lmdbjava.*;    
    import java.io.File;
    import java.nio.ByteBuffer;
    
    public class TestLmdbJava {
    
        private long start;
        private long end;
        private int RUNS = 5_250_000;
        private final boolean CLOSE_DB = false;
        private final boolean PRINT_STATS = true;
        private String pathName = "./test_lmdbjava";
        private String combinedDbName = "combinedDB";
    
        public static void main(String[] args) {
            new TestLmdbJava().runTest();
        }
    
        private void runTest() {
            try {
                File path = new File(pathName);
                if (!path.exists()) {
                    path.mkdir();
                }
    
                start = System.currentTimeMillis();
                writeCombined();
                end = System.currentTimeMillis();
                System.out.println("took " + (end - start) + "ms or " + (end - start) / 1000f + "s");
    
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    
        private final ByteBuffer getKey(int i) {
            ByteBuffer key = ByteBuffer.allocateDirect(8);
            key.mark();
            key.putLong((long)i);
            key.reset();
            return key;
        }
    
        long MB = 1024L * 1024L;
        private Env<ByteBuffer> createEnv(File path) {
            return Env.create()
                    .setMapSize(10 * MB)
                    .setMaxDbs(2)
                    .open(path);
        }
    
        private Dbi<ByteBuffer> createDb(Env<ByteBuffer> env, String name) {
            return env.openDbi(name, DbiFlags.MDB_CREATE, DbiFlags.MDB_INTEGERKEY); // MDB_WRITEMAP
        }
    
        private void stats(Env<ByteBuffer> env, Dbi<ByteBuffer> db) {
            Txn<ByteBuffer> txn = env.txnRead();
            Stat stat = db.stat(txn);
            System.out.println(stat);
            txn.close();
        }
    
        public final void writeCombined() {
            File path = new File(pathName);
            Env env = createEnv(path);
            Dbi db = createDb(env, combinedDbName);
            if (PRINT_STATS) {
                stats(env, db);
            }
    
            try (final Txn<ByteBuffer> txn = env.txnWrite()) {
                for (int i = 0; i < RUNS; i++)  {
                    writeSingle(env, db, txn, i);
                }
                txn.commit();
            }
    
            if (PRINT_STATS) {
                stats(env, db);
            }
    
            if (CLOSE_DB) {
                db.close();
            }
        }
    
        private void writeSingle(Env env, Dbi db, Txn<ByteBuffer> txn, int i) {
            try {
                ByteBuffer key = getKey(i);
                byte[] array = new byte[] {0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
                ByteBuffer buffer = ByteBuffer.allocateDirect(10);
                for (int bi = 0; bi < array.length; bi++) {
                    buffer.put(array[bi]);
                }
                buffer.flip();
                db.put(txn, key, buffer);
    
            } catch (Env.MapFullException mfe) {
                System.err.println("Map full at " + i);
                txn.abort(); // any way to recover here?
                throw mfe;
            } catch (Exception e) {
                System.err.println("Exception happened at " + i);
                stats(env, db);
                throw e;
            }
        }
    }
```

**Comment by benalexau** [comment]
`Env.setMapSize(long)` passed through to the LMDB C library function `mdb_env_set_mapsize`, the full documentation of which can be found [here](http://www.lmdb.tech/doc/group__mdb.html#gaa2506ec8dab3d969b0e609cd82e619e5) and is quoted below:

> Set the size of the memory map to use for this environment.
>
> The size should be a multiple of the OS page size. The default is 10485760 bytes. The size of the memory map is also the maximum size of the database. The value should be chosen as large as possible, to accommodate future growth of the database. This function should be called after mdb_env_create() and before mdb_env_open(). It may be called at later times if no transactions are active in this process. Note that the library does not check for this condition, the caller must ensure it explicitly.
>
> The new size takes effect immediately for the current process but will not be persisted to any others until a write transaction has been committed by the current process. Also, only mapsize increases are persisted into the environment.
>
> If the mapsize is increased by another process, and data has grown beyond the range of the current mapsize, mdb_txn_begin() will return MDB_MAP_RESIZED. This function may be called with a size of zero to adopt the new size.
>
> Any attempt to set a size smaller than the space already consumed by the environment will be silently changed to the current size of the used space. 

As you can see, there restrictions around changing the runtime size of the database. Whether it's an option for your application will depend primarily on its inter-process and write transaction use.

When estimating you may like to read the [Understanding LMDB File Sizes and Memory Utilization](https://symas.com/understanding-lmdb-database-file-sizes-and-memory-utilization/) page.

It is customary to significantly over-estimate the size required for the `Env`. On some operating systems (eg Linux) LMDB uses a [sparse file](https://en.wikipedia.org/wiki/Sparse_file). This means its physical storage requirements on disk are much smaller than the `mapsize` you specified in the `Env`.

Historically Windows and MacOS did not support sparse files, [as described by Howard Chu](https://groups.google.com/forum/#!topic/caffe-users/0RKsTTYRGpQ) (the LMDB author). However there seems to be a [merged PR](https://github.com/willyd/lmdb/pull/2/files) which added such support for Windows.

I'd recommend you just set a very large value and check the actual disk space consumption is acceptable on your target operating system(s) in view of the sparse file handling.

Regarding the code you posted, a few quick observations:

* You should always `ByteBuffer.allocate(int)` just once. There's a big performance overhead of repeatedly allocating for each method call. Allocate once, keep it as a field, and use it repeatedly.
* The `MDB_INTEGERKEY` wants "numeric keys in native byte order". So that means Little Endian in most cases. Your `ByteBuffer.order()` on the other hand defaults to Big Endian. So you need to explicitly set the `ByteBuffer` order.
* Your code is more self-describing (and will be less error-prone should you change the key format in the future) if when specifying the `ByteBuffer` size you use a field like `Long.BYTES`.
* Rather than copying a `byte[]` content into the `ByteBuffer` one element at a time, it's more efficient and self-documenting to just call `ByteBuffer.put(bytes[])`.
* Another code documentation suggestion is rather than computing the size of a megabyte directly, at the cost of an extra dependency you can use [byteunits](https://github.com/JakeWharton/byteunits) (we use this in LmdbJava's tests).

Many of the above suggestions may not apply as this is probably POC / prototype code. But hopefully it's helpful nevertheless. Also next time you post a code fragment in GitHub, putting `java` immediately after the opening backticks (see the [GitHub Code Blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) page) will offer nice syntax highlighting.

**Comment by benalexau** [comment]
Can we close this ticket?
