### ISSUE TITLE
Releasing memory from DirectByteBuffers

### ISSUE THREAD

**Issue by ivenhov** [lmdbjava/lmdbjava#145]
Hi

This is more of question than a bug.
ByteBufferProxy has deallocate which does

```
    @Override
    protected final void deallocate(final ByteBuffer buff) {
      buff.order(BIG_ENDIAN);
      final ArrayDeque<ByteBuffer> queue = BUFFERS.get();
      queue.offer(buff);
    }
```
If queue is full and buffer is not released to the pool it will be subject to GC at some point.
In the past I've seen cases (not LMDB related) where native memory usage and lack of GC can cause OutOfMemory errors because OS may run out of memory.
My question is is this a deliberate choice not to clean ByteBuffers explicitly like in e.g.
https://github.com/undertow-io/undertow/blob/master/core/src/main/java/io/undertow/server/DirectByteBufferDeallocator.java

My other question is about allocate

```
    @Override
    protected final ByteBuffer allocate() {
      final ArrayDeque<ByteBuffer> queue = BUFFERS.get();
      final ByteBuffer buffer = queue.poll();

      if (buffer != null && buffer.capacity() >= 0) {
        return buffer;
      } else {
        return allocateDirect(0);
      }
    }
```

It seems it allocates 0 bytes for new buffer.
How does it satisfy capacity requirements from lmdb? Is that just to have it as a pointer?
Obviously I don't understand it well enough

Regards

**Comment by benalexau** [comment]
The buffers managed by `ByteBufferProxy` (or indeed any `BufferProxy`) are only used when LmdbJava needs to provide a thread with a view over some LMDB-stored data. There are multiple LMDB restrictions connected with such buffers, including them being read-only and the buffer only being valid until the earlier of the next LMDB call or the transaction ending or the environment being closed. There is one noteable exception to this, `Dbi.reserve(..)`, where LMDB allows the returned buffer to be written, but it's an advanced and infrequently used method.

As you noticed, `ByteBufferProxy` uses a `ThreadLocal` to store a 16 element `Deque` of Java `ByteBuffer`s. These buffers are directly allocated with a length of 0 bytes as they subsequently have their internal pointers reflectively or unsafely modified to point to the relevant LMDB-specified (and outside Java heap) memory location and size. As buffers are returned to the `Deque` (at the completion of each transaction) they can be reused without further allocations. Usual GC reachability rules apply. There is no native memory allocated by these `ByteBuffers` given they are 0 bytes. All the native memory is within the memory mapped file that LMDB controls.

While it is true that if the `Deque` is full the fallback behaviour is an allocation of an additional 0 byte buffer, in most applications the number of concurrent JVM threads accessing LMDB is kept to a minimum as a matter of best practice anyway. This is because having concurrent reader and writer threads will cause an increase in the size of the LMDB file due to its MVCC approach. In addition you can only ever have a single write transaction at a time, with subsequent write transactions being blocked until the earlier write transaction completes. It's therefore more efficient from a storage size perspective (and easier to reason about, log and troubleshoot) if you use Java locking primitives to coordinate multiple threads through a single thread that is responsible for controlling a given LmdbJava `Env`. You can certainly run as many threads as you like, but most workloads with allocation latency or GC considerations are very conscious of threading optimisations anyway (eg thread pinning, circular buffers, advanced queues etc).

Hope this helps give more context. If you have any more questions please add them.

**Comment by benalexau** [comment]
The buffers managed by `ByteBufferProxy` (or indeed any `BufferProxy`) are only used when LmdbJava needs to provide a thread with a view over some LMDB-stored data. There are multiple LMDB restrictions connected with such buffers, including them being read-only and the buffer only being valid until the earlier of the next LMDB call or the transaction ending or the environment being closed. There is one noteable exception to this, `Dbi.reserve(..)`, where LMDB allows the returned buffer to be written, but it's an advanced and infrequently used method.

As you noticed, `ByteBufferProxy` uses a `ThreadLocal` to store a 16 element `Deque` of Java `ByteBuffer`s. These buffers are directly allocated with a length of 0 bytes as they subsequently have their internal pointers reflectively or unsafely modified to point to the relevant LMDB-specified (and outside Java heap) memory location and size. As buffers are returned to the `Deque` (at the completion of each transaction) they can be reused without further allocations. Usual GC reachability rules apply. There is no native memory allocated by these `ByteBuffers` given they are 0 bytes. All the native memory is within the memory mapped file that LMDB controls.

While it is true that if the `Deque` is full the fallback behaviour is an allocation of an additional 0 byte buffer, please bear in mind the `Deque` is one per thread to start with and the ordinary usage will only ever use 2 buffers per thread (one for the key, one for the buffer). 

On the subject of threads, in most applications the number of concurrent JVM threads accessing LMDB is kept to a minimum as a matter of best practice anyway. This is because having concurrent reader and writer threads will cause an increase in the size of the LMDB file due to its MVCC approach. In addition you can only ever have a single write transaction at a time, with subsequent write transactions being blocked until the earlier write transaction completes. It's therefore more efficient from a storage size perspective (and easier to reason about, log and troubleshoot) if you use Java locking primitives to coordinate multiple threads through a single thread that is responsible for controlling a given LmdbJava `Env`. You can certainly run as many threads as you like, but most workloads with allocation latency or GC considerations are very conscious of threading optimisations anyway (eg thread pinning, circular buffers, advanced queues etc).

Hope this helps give more context. If you have any more questions please add them.

**Comment by benalexau** [comment]
The buffers managed by `ByteBufferProxy` (or indeed any `BufferProxy`) are only used when LmdbJava needs to provide a thread with a view over some LMDB-stored data. There are multiple LMDB restrictions connected with such buffers, including them being read-only and the buffer only being valid until the earlier of the next LMDB call or the transaction ending or the environment being closed. There is one noteable exception to this, `Dbi.reserve(..)`, where LMDB allows the returned buffer to be written, but it's an advanced and infrequently used method.

As you noticed, `ByteBufferProxy` uses a `ThreadLocal` to store a 16 element `Deque` of Java `ByteBuffer`s. These buffers are directly allocated with a length of 0 bytes as they subsequently have their internal pointers reflectively or unsafely modified to point to the relevant LMDB-specified (and outside Java heap) memory location and size. As buffers are returned to the `Deque` (at the completion of each transaction) they can be reused without further allocations. Usual GC reachability rules apply. There is no native memory allocated by these `ByteBuffers` given they are 0 bytes. All the native memory is within the memory mapped file that LMDB controls.

While it is true that if the `Deque` is full the fallback behaviour is an allocation of an additional 0 byte buffer, please bear in mind the `Deque` is one per thread to start with and the ordinary usage will only ever use 2 buffers per thread (one for the key, one for the value). 

On the subject of threads, in most applications the number of concurrent JVM threads accessing LMDB is kept to a minimum as a matter of best practice anyway. This is because having concurrent reader and writer threads will cause an increase in the size of the LMDB file due to its MVCC approach. In addition you can only ever have a single write transaction at a time, with subsequent write transactions being blocked until the earlier write transaction completes. It's therefore more efficient from a storage size perspective (and easier to reason about, log and troubleshoot) if you use Java locking primitives to coordinate multiple threads through a single thread that is responsible for controlling a given LmdbJava `Env`. You can certainly run as many threads as you like, but most workloads with allocation latency or GC considerations are very conscious of threading optimisations anyway (eg thread pinning, circular buffers, advanced queues etc).

Hope this helps give more context. If you have any more questions please add them.

**Comment by benalexau** [comment]
As an aside, in my applications I usually use write a DAO that uses Simple Binary Encoding (SBE) flyweights to represent the data. The DAO methods always accept a SBE flyweight provided by the caller. The DAO then copies the relevant data from the LMDB-provided buffers into the memory buffer that the SBE flyweight is wrapping. The LmdbJava returned buffers are therefore only momentarily accessed for that memory copying operation, and Java primitives are used to block other threads from using the DAO at the same time. It works well. While some would argue the copying operation is wasteful given SBE is an ideal flyweight representation of the LMDB buffer, it's not that expensive for the value sizes I'm using and it's much easier building applications if you can abstract away all the LMDB considerations (eg transactions, buffer lifecycles, multiple thread rules etc) behind the DAO.

**Comment by ivenhov** [comment]
Hi Ben

Thanks for your detailed response.
This is invaluable for me and gives me a better understanding of how internals of lmdbjava work.

Regarding threads in my application I took slightly different approach, which may or may not be a wise decision.
In my application incoming requests are handled by threads which in turns are querying or modifing LMDB directly, without 
any hand-over to additional threads e.g. from a thread pool.
Handling threads come and go but not at a crazy rate, like each request is a new thread.
The workload is predominantly read/search.

I'm using MDB_NOTLS option
According to the docs this:
	Tie reader locktable slots to Txn objects instead of to threads.

Could you explain implications of that particular option on memory and storage usage?
I'm assuming there should be no difference to using dedicated pool of threads?
Does NOTLS have any detrimental effect to be aware of?

Regarding SBE it's something that is on my radar.
Currently I'm using ByteBuffers or byte[] and copy encoded content back and forth to the application layer.
It's probably similar approach, trying to limit amount of time buffers from LMDB are exposed.

Thanks again and I appreciate your time and help on this.

**Comment by benalexau** [comment]
`MDB_NOTLS` means that the native LMDB library will not use thread local storage for tracking read transactions, instead relying on the calling application to present the correct read transaction handle. This allows you to do things like passing a transaction between threads, or having multiple concurrent read transactions in a single thread. 

`MDB_NOTLS` does not change the memory and storage use of LMDB. The considerations that I mentioned earlier still apply (eg only a single write transaction will be allowed at a time, concurrent read transactions when there is a write transaction occurring will cause the underlying database to grow in size etc).

**Comment by benalexau** [comment]
I'll close this one. Please feel free to open another issue if you have further queries.
