### ISSUE TITLE
Q: New release?

### ISSUE THREAD

**Issue by jubax** [lmdbjava/lmdbjava#149]
I noticed you updated lots of libraries in 2020. I'm wondering if you plan to create a new release soon?

Thank you

**Comment by benalexau** [comment]
Yes, in the next few days. I just want to allow a few days for people to try out snapshot releases (they're in the Sonatype OSSRH snapshots repository) and/or report any concerns with the changes.

**Comment by ghudo** [comment]
Hi @benalexau - I was also wondering if you'd consider producing an unshaded version of the jar (i.e. "org.lmdbjava/lmdbjava-unshaded" or whatever name suits) for the next release!

The shaded jar bundled with the native jars is good for beginners - but if you want to only include the native library for the OS you're targeting or want to modify the LMDB library version, then you really need an unshaded version. Additionally, an unshaded version would make it **much** easier to figure out which native LMDB library version you were running!

Thanks in advance ;-) And thanks for maintaining this library!

**Comment by benalexau** [comment]
@ghudo Unless the `lmdbjava.disable.extract` or `lmdbjava.native.lib` system properties have been set, LmdbJava will always load the native library from the classpath at a well-defined resource file location, `org/lmdbjava/lmdbjava-native-{os}.{extension}`. These files are shaded into the LmdbJava JAR for Linux, Windows and macOS and together consume less than one megabyte before compression. Given the resource file location includes the LmdbJava package prefix, other classpath elements (ie other JARs) should not provide a file with this particular name.

If a user sets the `lmdbjava.disable.extract` property, the shaded libraries will never be used and instead the LMDB native library will be expected in the operating system's normal location. Alternately if someone sets the `lmdbjava.native.lib` property, the native library will be loaded from that user-specified location. It is possible to set system properties both from the command line and in Java code before referencing the LmdbJava `Library` class. As such special situations (eg a preference to use an operating system packaged version or a self-compiled version) are accommodated despite the shading.

I currently prefer to retain the shading of the native libraries given they are easily ignored via system properties, their inclusion imposes minimal storage overhead, and it simplifies the end user experience by not needing to explicitly define the relevant operating system dependency. In addition if we were to provided an unshaded JAR at this stage it would likely result in future queries around which native library wrapper JAR should be used with which LmdbJava JAR version etc.

Having said all that, if you can expand on your concerns with the shaded version I'd be happy to consider it. The overall goal is for LmdbJava to be useful to the wider Java community and if the shading is causing concerns that I'm unaware of, I am of course happy to address this.

**Comment by nbnsucks** [comment]
Thanks @benalexau! You're a fount of knowledge - really appreciate your thorough answer ;-)

Many java libraries I use provide an unshaded version and I generally prefer having control over what's included into my final artifact. I understand why this isn't desirable for the wider Java community, just a very helpful option for those who want a bit more control.

**Comment by ghudo** [comment]
Thanks @benalexau! You're a fount of knowledge - really appreciate your thorough answer ;-)

Many java libraries I use provide an unshaded version and I generally prefer having control over what's included into my final artifact. I understand why this isn't desirable for the wider Java community, just a very helpful option for those who want a bit more control.

**Comment by benalexau** [comment]
There are build system techniques that can be used to exclude the native libraries from your final artifact. Two that immediately come to mind are creating your own `com.mycompany.lmdb` group that contains a subset of the official JAR as you wish, or using filtering when producing your own uber JAR.

As I write this the shaded `lmdbjava-0.8.0-SNAPSHOT.jar` is 440 KB, and the `original-lmdbjava-0.8.0-SNAPSHOT.jar` is 100 KB. We're therefore talking about an extra 330 KB for three native libraries. For that 330 KB your build system doesn't need to list any additional dependencies for whatever operating system(s) you wish to support. Plus assuming you're not going to rely on the operating system to provide the package (with associated installation effort and native library search path issues) you'd need to include at least one such native library dependency anyway, so you're at best only saving around 200 KB.

I'd encourage you to open a separate ticket to request the enhancement and that way others can more easily find the conversation and comment (especially as this ticket will be closed once I release 0.8.0). My hesitation in just creating an unshaded version right now is that I cannot identify what benefits would be achieved - especially given the very modest size implications that shading adds - but I do foresee additional support questions because of it. I hope that makes sense.

**Comment by benalexau** [comment]
0.8.0 is now released and available for download from Maven Central: https://repo1.maven.org/maven2/org/lmdbjava/lmdbjava/
