### ISSUE TITLE
Can I limit the size of Shared memory it uses?

### ISSUE THREAD

**Issue by yechengkun1** [lmdbjava/lmdbjava#159]
I wan to put a  data with  total size of 10G into lmdb. 
How to do can I limit the size of the shared memory  uses to 2GB?

**Comment by benalexau** [comment]
LMDB can easily handle 10 GB of data, even on systems with only a fraction of that RAM. This is because it uses a [memory-mapped file](https://en.wikipedia.org/wiki/Memory-mapped_file), meaning the operating system will transparently balance available RAM between applications, cache, free memory etc. 

I've never needed to explicitly control the amount of memory that is allowed for memory-mapped files, although there are operating system directives that allow such control. Such operating system controls are not provided via LmdbJava or the LMDB C APIs.

It's probably preferable to just allow the OS to take care of allocating the memory unless you're running into a specific issue.

**Comment by yechengkun1** [comment]
由于我将使用LMDBJAVA的进程放在YARN上执行,当mmap使用的RAM超过mapreduce.map.memory.mb的限制,
yarn会杀死进程.  
这个问题困扰着我,您能给些建议吗?

**Comment by yechengkun1** [comment]
> LMDB can easily handle 10 GB of data, even on systems with only a fraction of that RAM. This is because it uses a [memory-mapped file](https://en.wikipedia.org/wiki/Memory-mapped_file), meaning the operating system will transparently balance available RAM between applications, cache, free memory etc.
> 
> I've never needed to explicitly control the amount of memory that is allowed for memory-mapped files, although there are operating system directives that allow such control. Such operating system controls are not provided via LmdbJava or the LMDB C APIs.
> 
> It's probably preferable to just allow the OS to take care of allocating the memory unless you're running into a specific issue.


Since I will put the process using LMDBJAVA on YARN execution, when the RAM used by mmap exceeds the mapreduce.map.memory.mb limit,
Yarn kills the process.
This problem is bothering me. Can you give me some advice?

**Comment by benalexau** [comment]
[Understanding LMDB Database File Sizes and Memory Utilisation](https://symas.com/understanding-lmdb-database-file-sizes-and-memory-utilization/) has more background about how LMDB uses memory.

As memory mapping is fundamental to how LMDB works, there are no tuning controls provided by the LMDB API for this. In turn LmdbJava - which is just native library wrapper over LMDB - does not offer any controls to limit the memory mapping either. 

Given memory mapped files are commonly used in many libraries and applications, I think this question is better directed to the Yarn documentation or community and I will close this ticket.

**Comment by yechengkun1** [comment]
thank you for your response.
