### ISSUE TITLE
Exception when using parent transactions

### ISSUE THREAD

**Issue by pstutz** [lmdbjava/lmdbjava#35]
I can't get parent transactions to work. This is the Scala code I run:
```scala
object ParentTxnProblem extends App {
  val db =  org.lmdbjava.Env.create
  val testFolder = new java.io.File("./test")
  testFolder.mkdir
  val env = db.open(testFolder)
  val parentTxn = env.txnRead
  val childTxn = env.txn(parentTxn, org.lmdbjava.TxnFlags.MDB_RDONLY_TXN)
}
```

This is the output of running the above with the current `0.0.5-SNAPSHOT` from Sonatype:
```
Exception in thread "main" org.lmdbjava.LmdbNativeException$ConstantDerviedException: Platform constant error code: EINVAL (22)
	at org.lmdbjava.ResultCodeMapper.checkRc(ResultCodeMapper.java:113)
	at org.lmdbjava.Txn.<init>(Txn.java:73)
	at org.lmdbjava.Env.txn(Env.java:274)
	at last line of example code above
```

Am I doing something wrong or is there an issue with parent transactions? Thanks a lot for your time.

**Comment by benalexau** [comment]
I receive the same error code when add the following to the project's `TxnTest`:

```  @Test
  public void txParentRO() {
    final Txn<ByteBuffer> txRoot = env.txnRead();
    final Txn<ByteBuffer> txChild = env.txn(txRoot, MDB_RDONLY_TXN);
    assertThat(txRoot.getParent(), is(nullValue()));
    assertThat(txChild.getParent(), is(txRoot));
  }
```

LmdbJava doesn't do very much behind-the-scenes aside from pass the transaction parent handle through to the LMDB C library and request a new transaction. As such I'm wondering if it's even possible to nest a RO transaction inside another RO transaction. I don't have time to test this, but if you were interested you could clone https://github.com/LMDB/lmdb and adapt a C test to verify.

More generally I am wondering why you'd want to nest a RO transaction inside another RO transaction in the first place? Generally you want RO transactions to be as short-lived as possible, as any concurrent write transaction will grow the file size. Also RO transactions can be efficiently reused without further object allocation costs via `Transaction.reset()` then `Transaction.renew()`.

**Comment by pstutz** [comment]
Hi Ben, thank you very much for looking into this.

The use case is to be able to have multiple threads read concurrently from the same DB version. The first approach was to hope that the thread-local stuff in LMDB will take care of it and use the same txn object. That didn't work, as some txn state seems to have gotten corrupted.

Next idea: Use the `MDB_NOTLS` flag and manage my own thread-local child transactions with a shared parent transaction to guarantee the same version. And this is how far I got. If there's a better way to do concurrent reads from the same version I would really appreciate your feedback.

**Comment by benalexau** [comment]
I am not aware of any approach that allows different threads to have LMDB transactions that point to the same initial version.

If the write workload can be coordinated from the JVM, a workaround would be to start your threads, allocate each a RO transaction at the start of each thread, then start your RW transaction in the writer thread. At suitable checkpoints use Java threading (eg barriers) to have all RO transactions reset and renew. However this would mean the writes grow the LMDB file size, as you have readers at the same time as a writer (MVCC requirement).

Another idea would be a DAO singleton that hides a single, shared RO transaction that is allocated with `MDB_NOTLS`. All threads would use DAO methods that internally lock around the RO `Txn`. The methods would return populated objects or buffer copies so that subsequent movement of the DAO `Cursor` (or `Dbi` as you feel is optimal for your use case) does not cause an error. This can be inexpensive from a performance perspective if you take care to preallocate (and reuse) flyweight objects and buffers.

In my own LmdbJava applications I have very distinct read and write phases. I am mostly dealing with huge amounts of financial market data and I store "current day" in a temporary LMDB file. I don't worry about optimising the current day file (eg concurrent readers causing extra page allocations, absence of integer compression, minimal indexing efficiency etc), as it's only a single day and it comfortably fits in RAM anyway. After the current day ends, a batch job moves the current day to a long-term history database. This separation of current day vs long-term resolves a lot of design challenges and provides substantial efficiency gains via `MDB_APPEND`. Your application might also be suitable for a multi-stage data layout.

Unsure if the above is much help, but if you wish to try to RO parent with RO child transaction approach I'd encourage you to try it in C as mentioned earlier. If it works there I am happy to spend more time investigating what's going wrong on the Java side.

**Comment by krisskross** [comment]
Reusing the same tx from multiple threads should work with the `MDB_NOTLS` flag.

**Comment by pstutz** [comment]
Hi Ben, thank you very much for outlining different solutions. I think the first approach might work well and it would even save the currently required reset/renew of read transactions. The use case is an analytics-focused parallel graph database, and after the initial loading I expect the workload to be dominated by reads. I'll try that.

**Comment by pstutz** [comment]
Hi Kristoffer, thanks for the suggestion. I tried that and whilst it's possible that I made a mistake I suspect that the transaction objects can get corrupted when used concurrently. The [LMDB documentation](https://github.com/LMDB/lmdb/blob/mdb.master/libraries/liblmdb/intro.doc) says that `A transaction must only be used by one thread at a time.`, so I didn't investigate any further.

**Comment by krisskross** [comment]
Yes, but this does not apply for `MDB_NOTLS` flag. Just make sure to not close/commit/abort the tx before all threads are done with it.

**Comment by pstutz** [comment]
I'll give it another try, thanks!

**Comment by pstutz** [comment]
I just tried using a single read transaction concurrently with `MDB_NOTLS` and get `BufferUnderflowException`s. I suspect that the cursor state is stored in a way such that concurrent accesses can interfere.

**Comment by krisskross** [comment]
That doesn't sound like an exception that lmdbjava or lmdb would throw. Can you show me the complete stack trace?

**Comment by pstutz** [comment]
This is the complete stack trace:
```
java.nio.BufferUnderflowException
	at java.nio.Buffer.nextGetIndex(Buffer.java:506)
	at java.nio.DirectByteBuffer.getLong(DirectByteBuffer.java:772)
	at com.deepgraphdb.index.LmdbIndexStore.mapValues(LmdbIndexStore.scala:139)
	at com.deepgraphdb.index.LmdbIndexStore.mapValues(LmdbIndexStore.scala:27)
	at com.deepgraphdb.index.Index.mapDeltas(Index.scala:26)
	at com.deepgraphdb.QueryTask.compute(QueryTask.scala:31)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

This is the `mapValues` function, line 139 is `val value = values.getLong`:
```
  def mapValues[G](k: TriplePattern, m: Long => G)(implicit txn: Txn[ByteBuffer]): List[G] = {
    val key = serialized(k)
    val c = db.openCursor(txn)
    val keyExists = c.get(key, MDB_SET)
    if (keyExists) {
      c.seek(MDB_GET_MULTIPLE)
      var results = List.empty[G]
      do {
        val values = c.`val`
        while (values.hasRemaining) {
          val value = values.getLong
          val result = m(value)
          if (result != null) {
            results = result :: results
          }
        }
      } while (c.seek(MDB_NEXT_MULTIPLE))
      c.close
      results
    } else {
      c.close
      Nil
    }
  }
```

Thank you very much for looking at this, I really appreciate it.

**Comment by krisskross** [comment]
It looks like your are trying to reading the buffer too far, i.e. outside its limit.

**Comment by pstutz** [comment]
Yes. And the same tests work fine when each thread gets its own thread-local read transaction.

**Comment by pstutz** [comment]
I assumed that some of the cursor state is stored on the transaction object and that maybe the values reference is then shared in a bad way between threads, which would explain the reading outside the limit in spite of `hasRemaining` being true.

**Comment by krisskross** [comment]
Yes, I think you're right. The state should probably belong to the cursor. Let me have another look later tonight.

**Comment by krisskross** [comment]
@benalexau I think we should support sharing transactions between threads. But its not possible since the key and value cache is maintained on transaction. We could consider have another cache for each cursor. Users could in principle share cursors between threads but it makes no sense to me to navigate cursors concurrently? Maybe disallow it by documenting as a constraint?

Thoughts?

**Comment by krisskross** [comment]
By the way, this is how I implemented it in lmdbjni - so i'm confident that it works. But I cannot recall if we had a strong incitement to put the cache on transaction?

**Comment by benalexau** [comment]
@krisskross there was no particular reason for it being on `Txn`. It just seemed the most natural place given the typical use is LMDB TLS. Please feel free to improve the design.

**Comment by krisskross** [comment]
Ok, thanks. I don't have time at the moment. But ill take a stab after new year.

**Comment by benalexau** [comment]
Are we OK to close this ticket now PR #36 is closed?

**Comment by pstutz** [comment]
Thank you very much for the help. I'm now reusing cursors from a pool and renew them with the right transaction. The performance is very good. A thing I wonder about API-wise is why I initially get a cursor only from a Dbi (and not Env/Txn), but can later renew it with just a transaction.

**Comment by benalexau** [comment]
A `Cursor` is for a specific database (ie map / table) so you need to get it from the `Dbi` so LMDB knows which database you wish to interact with. This is reflected in the underlying [mdb_cursor_open](http://104.237.133.194/doc/group__mdb.html#ga9ff5d7bd42557fd5ee235dc1d62613aa) C function signature.

**Comment by pstutz** [comment]
Thanks for the explanation.
