### ISSUE TITLE
TutorialTest tutorial5

### ISSUE THREAD

**Issue by Maurice-Betzel** [lmdbjava/lmdbjava#53]
In tutorial 5 it states "Duplicate support requires both keys and values to be <= max key size". The Dbi is opened only with MDB_DUPSORT. Should this not result in being able to add arbitrary value sizes as LMDB also allows MDB_DUPFIXED for fixes sizes?

**Comment by benalexau** [comment]
Quoting the LMDB docs for [MDB_val](http://www.lmdb.tech/doc/group__mdb.html#structMDB__val):

> Key sizes must be between 1 and mdb_env_get_maxkeysize() inclusive. The same applies to data sizes in databases with the MDB_DUPSORT flag. Other data items can in theory be from 0 to 0xffffffff bytes long. 

The docs for [mdb_dbi_open](http://www.lmdb.tech/doc/group__mdb.html#gac08cad5b096925642ca359a6d6f0562a) state:

> MDB_DUPFIXED: This flag may only be used in combination with MDB_DUPSORT. This option tells the library that the data items for this database are all the same size, which allows further optimizations in storage and retrieval. When all data items are the same size, the MDB_GET_MULTIPLE and MDB_NEXT_MULTIPLE cursor operations may be used to retrieve multiple items at once. 

As such I believe the `TutorialTest` comment is correct. Please feel free to comment here if you find otherwise and I'll reopen the ticket for investigation.
