### ISSUE TITLE
What if number of DBs is unknown?

### ISSUE THREAD

**Issue by buko** [lmdbjava/lmdbjava#66]
Big fan of the project. Thanks for making such a great persistence solution!

Question: 
Normally when you create an Environment  you must specify the number of DBs eg:

```java
final Env<ByteBuffer> env = create()
        // LMDB also needs to know how large our DB might be. Over-estimating is OK.
        .setMapSize(10_485_760)
        // LMDB also needs to know how many DBs (Dbi) we want to store in this Env.
        .setMaxDbs(1)
```

We're leaning towards a model (data is very unstructured) that calls for creating a DBI for an unknown number of entities. Entities are identified by UUIDs and there might be 1 persisted... or millions.

The simplest thing to do might be to simply call setMaxDbs(Integer.MAX) (or some other very high number).

Is this okay?

What might be the impact on performance due to passing a very high number to maxDbs?

**Comment by benalexau** [comment]
Quoting the C API comments for [mdb_env_set_maxdbs](http://www.lmdb.tech/doc/group__mdb.html#gaa2fc2f1f37cb1115e733b62cab2fcdbc):

> Currently a moderate number of slots are cheap but a huge number gets expensive: 7-120 words per transaction, and every mdb_dbi_open() does a linear search of the opened slots. 

As such I wouldn't recommend having too many DBIs in a single `Env`.

> Entities are identified by UUIDs and there might be 1 persisted... or millions.

LMDB is a sorted key-value store, so generally you will benefit by assigning keys in a use case meaningful way. That way cursors can inexpensively iterate over your data set, which is important when you need to scan to satisfy a filter. You can also gain some storage and insertion speed efficiencies if you know you will be inserting in key order.

For example most (99%) of my data is time series. Skimming lots of finer details, we have keys that start with a numeric day identifier (think an epoch) and end with an entity identifier. Then all data for one entity on one day is within one key-value pair. What complicates this use case is we have no way of knowing which entities will send data on a given "live" day, or how much data they will send. So we store the current day in its own LMDB database, and at the end of the day (when we know how much data was actually sent) we migrate that data to the long-term database. This migration occurs in key order, therefore enabling the historical database to remain as small as practical as LMDB detects we're inserting in key order and it therefore doesn't allocate unnecessary free space (as it would if random keys were being inserted).

If you can describe what you're trying to store, we can probably offer some suggestions.

**Comment by krisskross** [comment]
If you do not need to transactional data sync across databases you could also create separate `Env` instances in different directories and use them in the same way as @benalexau described. 

This approach doesn't have a limitation on the number of `Env`/`Database` created.

**Comment by buko** [comment]
The original idea was to have a very generic Entity/Attribute store.

One DBI would simply store the status of an Entity:

ENTITES(UUID=EntityState)


Each Entity would then get its own DBi:
ENTITY.$UUID(AttributeName=AttributeValue)

An Entity also needs to know about the Entites in its neighborhood. This could be done using compound keys:

NEIGHBORHOOD(EntityID.NeighborID=NeighborData)

That was the basic idea.

We certainly could store everything in one Db... there was concern about the cost of calculating compound keys (we can precompute AttributeName keys but if they include an EntityID then we'll need to do some 'key serialization' logic.)

**Comment by benalexau** [comment]
> there was concern about the cost of calculating compound keys

Don't be. Just preallocate a re-usable key buffer and use offsets. For example, if you needed an integer prefix and then a UUID, you'd need a key buffer of 12 bytes. At offset 0 you'd write the integer, and at offset 4 you'd write the UUID. This is incredibly inexpensive, as the entire 12 bytes will be in the same cache line (on that issue you should allocate a 64 byte buffer but only use the first 12 bytes), and you can use a bounds-check disabled buffer (eg Agrona `UnsafeBuffer`) if you were really concerned. As an aside Agrona has static methods that hide the cache line (eg [allocateDirectAligned](https://github.com/real-logic/agrona/blob/6ce49856869b3da06699b960318aae714987fc76/agrona/src/main/java/org/agrona/BufferUtil.java#L126) can be used with `org.agrona.BitUtil.CACHE_LINE_LENGTH`).

If your keys are somewhat complex, I use and recommend [Simple Binary Encoding](https://github.com/real-logic/simple-binary-encoding). SBE generates encoder and decoder flyweights that can also handle schema changes, recurring fields, user-defined types / enums etc. It shields you from needing to keep track of field offsets and imposes no overhead compared with hand-written code. SBE is overkill if you have simple needs though. We use our own DAO code generator (which uses the offset approaches for automatically-encoded primary keys and index keys) and SBE for the value encoding.

Our generated DAO pattern has found the transaction capabilities of LMDB makes it quite simple to maintain multiple index tables. A typical pattern for a generated update method is basically:

1. Start a write transaction
2. Build primary key buffer from the passed entity object
3. Fetch existing record (using the primary key buffer) from the data table
4. Generate all index keys for the existing record
5. Drop all index records (using the index key buffers) from the index tables
6. Write the modified record into the data table
7. Generate new index keys for the modified record
8. Write the index records into the index tables (the values are the PK to the data table)
9. Commit

Sure that's somewhat inefficient for writes because often we drop an index record and the insert exactly the same index record again, but the trade-off there is we're using a code generator so we want the generator to be correct and maintainable. Furthermore to be using LMDB at all means your use case is read-optimised, and writes are slower. If you need to be write-optimised and care less about reads, you're probably better off with a log structured merge type system such as LevelDB or its derivatives.

I share this because it sounds like you're trying to write a "generic" store, so having a way to differentiate your "index" keys from the "primary" keys is generally necessary. To finish off my DAO example, this shows how we do that:

```
  @Put(fw = InstrumentDecoder.class, pk = "global")
  void putInstrument(Txn<DirectBuffer> txn, DirectBuffer in);

  @Get(fw = InstrumentDecoder.class, key = "global")
  DirectBuffer getInstrument(Txn<DirectBuffer> txn, long global);

  @Iter(fw = InstrumentDecoder.class, key = "composite")
  DaoIterator findInstrumentByComposite(Txn<DirectBuffer> txn, KeyRangeType type,
                                        long composite);

  @Iter(fw = InstrumentDecoder.class, key = "shareClass")
  DaoIterator findInstrumentByShareClass(Txn<DirectBuffer> txn,
                                         KeyRangeType type, long shareClass);
```

Note the `fw` attribute is an SBE-generated flyweight, and the `pk` and `key` fields are found in the flyweight. Everything else is handed via runtime code generation. Our pattern is edit an SBE XML file, generate, write an annotated DAO interface, then use the annotated DAO interface with its runtime implementation. It's very rare to need to deal with LmdbJava APIs directly from domain code (the exception is our time series data, as that's 99% of our data volume and has extremely challenging storage and performance requirements).

> If you do not need to transactional data sync across databases you could also create separate Env instances in different directories

@krisskross noted the fundamental piece about a `Txn` cannot cross `Env`s. You can, if desired, also have different `Env`s in the same directory (although different physical data and lock files) if you use [MDB_NOSUBDIR](https://github.com/lmdbjava/lmdbjava/blob/master/src/main/java/org/lmdbjava/EnvFlags.java#L38).

**Comment by buko** [comment]
@benalexau Thanks very much. You've given us a lot to think about. Definitely like the idea of a metamodel that links primary keys and indexes.
