### ISSUE TITLE
Buffers, Copying and Reuse

### ISSUE THREAD

**Issue by jbee** [lmdbjava/lmdbjava#81]
This is a pure question to get my understanding straight. 

In connection with LMDB the is talk about _zero copying_. 
My understanding would be that one can use a off-heap buffer that points directly at the memory LMDB uses for a key or value. In a read-only case we would not have to copy such a buffer for reading from it. The Java class handling it would have that pointer and some fields for the position etcetera. What about writing? Is there any coping? Why not?

Netty and Agrona provide such a buffers. What is the minimal way to use one of these? Copy code from somewhere?

If on the other hand one uses a JRE `DirectByteBuffer` we allocate off-heap memory and the key or value is copied from LMDBs memory into the allocated memory or vice versa.

If that is correct I got the idea that I can have a single JRE buffer allocated for values when writing that I reuse all the time since there only could be one thread writing at a time anyway. Is this good practice or a bad idea? If so why?

**Comment by benalexau** [comment]
LMDB (the C library) controls the off-heap location where entries have been stored. This memory is strictly read-only from an LMDB client perspective, so the zero copy refers to the ability to read an entry without copying it from the LMDB off-heap memory to some other memory for read access.

LmdbJava includes Agrona support which wraps the LMDB off-heap memory for read operations. There is a Netty buffer in the test directory you can use if desired. The direct `ByteBuffer` support is achieved by internally changing the `ByteBuffer` memory address to point to the relevant LMDB off-heap memory address and length. So it is also zero copy for read operations.

For write operations it is up to you how you manage the source buffers you wish to write. It is typical to reuse the same buffer. During writes LMDB must determine which off-heap page it wishes to store the key and value in, after which it will copy the data from your source buffer to that off-heap address. Once the write has completed the source buffer is available for further use.

There is an advanced use (see `Dbi.reserve(..)`) which allows you to write the key and a size for the value, after which the returned buffer can be used to directly write the value to the LMDB-selected off-heap location. If you have extreme performance requirements you could use this to avoid the value copy (the key copy is still unavoidable), but you'd have to benchmark if it were truly faster. I have my doubts given there are 2 JNI calls (one for reserve and another for put) rather than just 1 JNI call (put), the just-used source buffer is likely in CPU cache anyway, and the tree balancing effort is likely to be vastly more overhead than the cost of a memory copy. However you'd need to benchmark it with your value sizes, total database size, and write patterns (there can be performance surprises due to tree balancing overhead).

**Comment by jbee** [comment]
Thank you for the clear explanation. Maybe one follow up question: If `ByteBuffer` is zero copying why would one use another buffer? For the java API on that buffer?

**Comment by benalexau** [comment]
A few reasons to use something other than `ByteBuffer`:

1. Richer APIs
2. Integration with other libraries that use those buffers (eg Simple Binary Encoding, Aeron)
3. No bounds checking overhead

On the other hand `ByteBuffer` is part of the JRE and bounds checking is rarely measurably expensive. So the bigger consideration is likely how you're using the buffer in the application itself.

**Comment by jbee** [comment]
Thanks again for the explanation. No further questions ;)
