### ISSUE TITLE
Consider using MDBX

### ISSUE THREAD

**Issue by leventov** [lmdbjava/lmdbjava#85]
https://github.com/leo-yuriev/libmdbx is a fork of LMDB that is being developed much more actively, and [implements a number of improvements over LMDB](https://github.com/leo-yuriev/libmdbx#improvements-over-lmdb).

cc @leo-yuriev

**Comment by krisskross** [comment]
Interesting since it doesn't change the API. If our current build is compatible it should be quite easy to give it a go. I'll try to reserve a few hours on in the near future.

**Comment by benalexau** [comment]
I see there is a JNI wrapper in the [mdbxjni](https://github.com/castortech/mdbxjni) project. We should add it to the benchmark project when it has a Maven Central release (not a snapshot).

I'd have liked to see the [performance comparisons](https://github.com/leo-yuriev/libmdbx#performance-comparison) include LMDB.

**Comment by benalexau** [comment]
`libmdbx` project is now read-only with a statement "The next version is under active non-public development from scratch and will be released as MithrilDB". Also the `mdbxjni` Java wrapper hasn't seen any commits since 2021.

I'm unsure there is anything we can really do to progress this issue so I will close it.
