### ISSUE TITLE
Is LMDB backup consistent when read/write/deletes are happening?

### ISSUE THREAD

**Issue by brary** [lmdbjava/lmdbjava#87]
So LmDb provides this backup feature where we can create a backup only on local machine(correct me if I am wrong) with some destination path. So I have below questions regarding feature.

1. Will this backup be consistent if writes and deletes are happening simultaneously? I have read that writes may significantly increase the size of backup but we are sure it will be consistent and will backup writes till a certain point?

2. Is there a way we can create remote backups like RocksDb provides backup to HDFS inherently in their code?

3. If we open LMDB in readonly mode and copy the files to some other machine, when we create an lmdb instance with path to the copied files, will it pickup those as it's files and will it be consistent?

Thanks

**Comment by benalexau** [comment]
A backup created with `Env.copy(File, CopyFlags...)` delegates to LMDB's `mdb_env_copy2` function. This function creates a read-only transaction and performs the copy. As such it has the same consistency guarantees as normal LMDB use, in particular there can only be a single write transaction at a time (other write transactions will be blocked from commencing) and a read-only transaction occurring simultaneously with a write transaction will cause file growth. See the [LMDB Caveats](http://www.lmdb.tech/doc/index.html#caveats_sec) for more details.

As LmdbJava simply passes the `File` path to the LMDB function, there is no special support for backing up to a remote file system. You'd have to test for yourself whether presenting a path to a remote file system works or not. Certainly the aforementioned LMDB Caveats document mentions:

> Do not use LMDB databases on remote filesystems, even between processes on the same host. This breaks flock() on some OSes, possibly memory map sync, and certainly sync between programs on different hosts.

As such I wouldn't recommend it, but as it's a copy destination (as opposed to read-write use) it _might_ be feasible.

If you generated the database locally and then copied the file to a remote machine and opened it on that remote machine from a file system local to that remote machine, the database should have the same state as at the commencement of the `Env.copy(File, CopyFlags...)` method call.

**Comment by benalexau** [comment]
If you close your running `Txn`s, `Dbi`s and `Env`, then open the `Env` with `EnvFlags.MDB_RDONLY_ENV`, I cannot see any problem with copying the data file to another machine for warm standby purposes. However it does seem at first glance a complicated option given `Env.copy(File, CopyFlags...)` offers an easier way to acquire a transactionally-consistent snapshot of the data and other read-only transactions can continue to operate on the database even while the method is being invoked. I guess if you're space constrained on the local file system it would be useful.

There might be other approaches to your high availability goals. For example, I've previously used [Apache DistributedLog](https://bookkeeper.apache.org/distributedlog/) in a high availability situation where each node maintained its own independent LMDB database that was built purely from the journal (and periodically a follower node would be shut down and its LMDB database copied to blob storage for recovery purposes and seeding new nodes, rather than requiring new nodes to replay every historical event into blank LMDB databases). I also frequently use a different LMDB database file for successive time periods and take the end of each time period as a good opportunity to rewrite the data in a permanent immutable file (adding indexes, summaries and integer compression while also eliminating the now-unnecessary free space left by LMDB to reduce write-time page splits). In both of these cases the backup approach provided other important features to the broader architecture.

**Comment by brary** [comment]
Thanks.
