### ISSUE TITLE
key/data pair already exists

### ISSUE THREAD

**Issue by tamerh** [lmdbjava/lmdbjava#94]
Hello,

I have a sorted large data set and some keys have multiple values. I am setting dbi and put flags as

DbiFlags.MDB_CREATE;
DbiFlags.MDB_DUPSORT;

PutFlags.MDB_APPEND ;
PutFlags.MDB_APPENDDUP

but i am getting key/data pair already exists exception.

If i remove the put flags it is working fine. Shouldn't be working also with put flags? 

Thanks

**Comment by krisskross** [comment]
Please provide complete test code. Its much easier/faster to diagnose that way.

**Comment by seancarroll** [comment]
From the [LMDB docs](http://www.lmdb.tech/doc/group__mdb.html)

> MDB_APPEND - append the given key/data pair to the end of the database. This option allows fast bulk loading when keys are already known to be in the correct order. Loading unsorted keys with this flag will cause a MDB_KEYEXIST error.
> MDB_APPENDDUP - as above, but for sorted dup data.

My interpretation of that is you would use `MDB_APPENDDUP ` when using `MDB_DUPSORT` and otherwise you would use `MDB_APPEND` but you wouldn't use both `MDB_APPENDDUP` and `MDB_APPEND` together.

There is a test for the `MDB_APPENDDUP` case here https://github.com/lmdbjava/lmdbjava/blob/master/src/test/java/org/lmdbjava/CursorTest.java#L97. I couldn't find a test case for `MDB_APPEND`.

Modifying the test case above two include both put flags

```
  @Test
  public void dupSortWithAppendAndAppendDup() {
    final Dbi<ByteBuffer> db = env.openDbi(DB_1, MDB_CREATE, MDB_DUPSORT);
    try (Txn<ByteBuffer> txn = env.txnWrite()) {
      final Cursor<ByteBuffer> c = db.openCursor(txn);
      c.put(bb(1), bb(2), MDB_APPENDDUP, MDB_APPEND);
      assertThat(c.count(), is(1L));
      c.put(bb(1), bb(4), MDB_APPENDDUP, MDB_APPEND);
      c.put(bb(1), bb(6), MDB_APPENDDUP, MDB_APPEND);
      assertThat(c.count(), is(3L));
      c.put(bb(2), bb(1), MDB_APPENDDUP, MDB_APPEND);
      c.put(bb(2), bb(2), MDB_APPENDDUP, MDB_APPEND);
      assertThat(c.count(), is(2L));
    }
  }
```

This does fails with `org.lmdbjava.Dbi$KeyExistsException: key/data pair already exists (-30799)` but I'm not sure this is a valid scenario or what the expected outcome is.

**Comment by benalexau** [comment]
@seancarroll thanks for clarifying and assisting with a test case.

@tamerh did you have any outstanding queries in relation to this issue, or can it be closed?

**Comment by tamerh** [comment]
yes it can be closed thank you for the responses. I thought i had to use both MDB_APPENDDUP and MDB_APPEND together if i have duplicate values.
